export type Country = "Zimbabwe" | "Zambia" | "South Africa" | "Yemen" | "Vanuatu" | "Vietnam" | "Venezuela" | "Uzbekistan" | "United States of America" | "Uruguay" | "Ukraine" | "Uganda" | "United Republic of Tanzania" | "Taiwan" | "Turkey" | "Tunisia" | "Trinidad and Tobago" | "Timor Leste" | "Turkmenistan" | "Tajikistan" | "Thailand" | "Togo" | "Chad" | "Syria" | "Eswatini" | "Sweden" | "Slovenia" | "Slovakia" | "Suriname" | "Serbia" | "Somalia" | "Somaliland" | "El Salvador" | "Sierra Leone" | "Solomon Islands" | "Senegal" | "South Sudan" | "Sudan" | "Saudi Arabia" | "Western Sahara" | "Rwanda" | "Russia" | "Romania" | "Qatar" | "Paraguay" | "Portugal" | "North Korea" | "Puerto Rico" | "Poland" | "Papua New Guinea" | "Philippines" | "Peru" | "Panama" | "Pakistan" | "Oman" | "New Zealand" | "Nepal" | "Norway" | "Netherlands" | "Nicaragua" | "Nigeria" | "Niger" | "New Caledonia" | "Namibia" | "Malaysia" | "Malawi" | "Mauritania" | "Mozambique" | "Mongolia" | "Montenegro" | "Myanmar" | "Malta" | "Mali" | "North Macedonia" | "Mexico" | "Madagascar" | "Moldova" | "Morocco" | "Latvia" | "Luxembourg" | "Lithuania" | "Lesotho" | "Sri Lanka" | "Libya" | "Liberia" | "Lebanon" | "Laos" | "Kuwait" | "Kosovo" | "South Korea" | "Cambodia" | "Kyrgyzstan" | "Kenya" | "Kazakhstan" | "Japan" | "Jordan" | "Jamaica" | "Italy" | "Israel" | "Iceland" | "Iraq" | "Iran" | "Ireland" | "India" | "Indonesia" | "Hungary" | "Haiti" | "Croatia" | "Honduras" | "Guyana" | "French Guiana" | "Guatemala" | "Greenland" | "Greece" | "Equatorial Guinea" | "Guinea Bissau" | "Gambia" | "Guinea" | "Ghana" | "Georgia" | "United Kingdom" | "Gabon" | "France" | "Falkland Islands" | "Fiji" | "Finland" | "Ethiopia" | "Estonia" | "Spain" | "Eritrea" | "Egypt" | "Ecuador" | "Algeria" | "Dominican Republic" | "Denmark" | "Djibouti" | "Germany" | "Czech Republic" | "Cyprus" | "Northern Cyprus" | "Cuba" | "Costa Rica" | "Colombia" | "Republic of the Congo" | "Democratic Republic of the Congo" | "Cameroon" | "Ivory Coast" | "China" | "Chile" | "Switzerland" | "Canada" | "Central African Republic" | "Botswana" | "Bhutan" | "Brunei" | "Brazil" | "Bolivia" | "Bermuda" | "Belize" | "Belarus" | "Bosnia and Herzegovina" | "The Bahamas" | "Bulgaria" | "Bangladesh" | "Burkina Faso" | "Benin" | "Belgium" | "Burundi" | "Azerbaijan" | "Austria" | "Australia" | "French Southern and Antarctic Lands" | "Antarctica" | "Armenia" | "Argentina" | "United Arab Emirates" | "Albania" | "Angola" | "Afghanistan";


export interface GridIntensity {
  [country: string]: number | null;
}

// ** Information gathered from https://app.electricitymaps.com/map/all/yearly (2024) **
export const GRID_INTENSITY: GridIntensity = {
"Zimbabwe": 258,
"Zambia": 119,
"South Africa": 713,
"Yemen": 522,
"Vanuatu": 533,
"Vietnam": 442,
"Venezuela": 126,
"Uzbekistan": 472,
"United States of America": 403,
"Uruguay": 53,
"Ukraine": null,
"Uganda": 60,
"United Republic of Tanzania": 361,
"Taiwan": 525,
"Turkey": 423,
"Tunisia": 482,
"Trinidad and Tobago": 490,
"Timor Leste": 649,
"Turkmenistan": 490,
"Tajikistan": 75,
"Thailand": 490,
"Togo": 396,
"Chad": 637,
"Syria": 564,
"Eswatini": 106,
"Sweden": 23,
"Slovenia": 234,
"Slovakia": 240,
"Suriname": 242,
"Serbia": 511,
"Somalia": 565,
"Somaliland": null,
"El Salvador": 248,
"Sierra Leone": 55,
"Solomon Islands": 632,
"Senegal": 572,
"South Sudan": 596,
"Sudan": 185,
"Saudi Arabia": 552,
"Western Sahara": null,
"Rwanda": 335,
"Russia": null,
"Romania": 321,
"Qatar": 490,
"Paraguay": 25,
"Portugal": 101,
"North Korea": 300,
"Puerto Rico": 360,
"Poland": 703,
"Papua New Guinea": 513,
"Philippines": 624,
"Peru": 186,
"Panama": 167,
"Pakistan": 260,
"Oman": 479,
"New Zealand": 112,
"Nepal": 117,
"Norway": 33,
"Netherlands": 263,
"Nicaragua": 311,
"Nigeria": 374,
"Niger": 658,
"New Caledonia": 543,
"Namibia": 43,
"Malaysia": 568,
"Malawi": 60,
"Mauritania": 519,
"Mozambique": 101,
"Mongolia": 746,
"Montenegro": 400,
"Myanmar": 335,
"Malta": 426,
"Mali": 414,
"North Macedonia": 481,
"Mexico": 392,
"Madagascar": 475,
"Moldova": 419,
"Morocco": 527,
"Latvia": 183,
"Luxembourg": 252,
"Lithuania": 165,
"Lesotho": 24,
"Sri Lanka": 405,
"Libya": 527,
"Liberia": 472,
"Lebanon": 307,
"Laos": 202,
"Kuwait": 515,
"Kosovo": 651,
"South Korea": 423,
"Cambodia": 273,
"Kyrgyzstan": 127,
"Kenya": 95,
"Kazakhstan": 592,
"Japan": 457,
"Jordan": 383,
"Jamaica": 487,
"Italy": 274,
"Israel": 492,
"Iceland": 28,
"Iraq": 563,
"Iran": 495,
"Ireland": 397,
"India": 617,
"Indonesia": 663,
"Hungary": 243,
"Haiti": 523,
"Croatia": 228,
"Honduras": 343,
"Guyana": 657,
"French Guiana": 410,
"Guatemala": 370,
"Greenland": 103,
"Greece": 325,
"Equatorial Guinea": 349,
"Guinea Bissau": 700,
"Gambia": 700,
"Guinea": 190,
"Ghana": 327,
"Georgia": 162,
"United Kingdom": 175,
"Gabon": 293,
"France": 33,
"Falkland Islands": 700,
"Fiji": 290,
"Finland": 76,
"Ethiopia": 24,
"Estonia": 291,
"Spain": 124,
"Eritrea": 633,
"Egypt": 450,
"Ecuador": 232,
"Algeria": 487,
"Dominican Republic": 563,
"Denmark": 124,
"Djibouti": 450,
"Germany": 334,
"Czech Republic": 481,
"Cyprus": 686,
"Northern Cyprus": null,
"Cuba": 607,
"Costa Rica": 94,
"Colombia": 95,
"Republic of the Congo": 398,
"Democratic Republic of the Congo": 398,
"Cameroon": 160,
"Ivory Coast": 389,
"China": 513,
"Chile": 236,
"Switzerland": 41,
"Canada": 132,
"Central African Republic": 24,
"Botswana": 811,
"Bhutan": 120,
"Brunei": 566,
"Brazil": 91,
"Bolivia": 333,
"Bermuda": null,
"Belize": 166,
"Belarus": 317,
"Bosnia and Herzegovina": 483,
"The Bahamas": 691,
"Bulgaria": 350,
"Bangladesh": 620,
"Burkina Faso": 577,
"Benin": 508,
"Belgium": 153,
"Burundi": 239,
"Azerbaijan": 431,
"Austria": 124,
"Australia": 489,
"French Southern and Antarctic Lands": null,
"Antarctica": null,
"Armenia": 208,
"Argentina": 380,
"United Arab Emirates": 383,
"Albania": 92,
"Angola": 177,
"Afghanistan": 121,
}
